dist: trusty
language: node_js
node_js:
  - "lts/*"
cache:
  yarn: true
  directories:
    - node_modules
jobs:
  include:
    - stage: pretest
      before_script: skip
      script:
        - commitlint-travis
        - yarn lint
      after_failure: skip
    - stage: test
      env: BROWSER=chrome
      addons:
        chrome: stable
    - stage: test
      env: BROWSER=firefox
      addons:
        firefox: latest
    - stage: deploy
      if: branch = master && type != pull_request
      before_script: skip
      script: yarn build
      after_failure: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: bash deploy.sh
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
  # Codecs needed for Firefox to play audio.
  - if [[ "$BROWSER" == "firefox" ]]; then sudo apt-get install -y -qq ubuntu-restricted-addons; fi
before_script:
  - |
    if [ $HEADLESS -eq 0 ]; then
      /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16
      # give xvfb some time to start
      sleep 3
      # Same as what we specified for Xvfb.
      export DISPLAY=:99.0
    fi
  # Build budle.js
  - yarn build
  - cp test/setup.js.travis test/setup.js
  # Increase the shared memory mountpoint. Chrome or something in the tests is
  # taking up more shared memory than is available which causes tests to fail.
  # See https://github.com/SeleniumHQ/docker-selenium/issues/431
  - sudo mount -o remount,size=64G /run/shm
script: yarn mocha --bail
# When the test script fails, push screen shots to a git branch.
after_failure: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR/travis-screenshots"
    git init
    git checkout -b travis-screenshots
    git add .
    git -c user.name="$GITHUB_USER" -c user.email='travis' commit -m 'Travis CI screenshots'
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG travis-screenshots 2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
