name: Cypress push and pull

on: [push, pull_request]

jobs:
  cypress-run:
    name: firefox
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2

      - name: Get yarn Cache Directory Path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@0865c47f36e68161719c5b124609996bb5c40129 # tag=v3
        # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: |
          yarn install

      - name: update test fixture
        run: yarn cy:gen:fix

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
          wait-on: http://127.0.0.1:8080
          browser: firefox
          headless: true
